project_id = "hgztcymscgyuekgsyyfe"

[functions.cycle-courier-webhook]
verify_jwt = false

[functions.quickbooks-oauth]
verify_jwt = false

[functions.inspectabike-webhook]
verify_jwt = false

[functions.typeform-oauth]
verify_jwt = false

[functions.typeform-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false
