project_id = "hgztcymscgyuekgsyyfe"

[functions.cycle-courier-webhook]
verify_jwt = false

[functions.cycle-courier-oauth]
verify_jwt = false

[functions.quickbooks-oauth]
verify_jwt = false

[functions.inspectabike-webhook]
verify_jwt = false

[functions.typeform-oauth]
verify_jwt = false

[functions.typeform-webhook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.shopify-install]
verify_jwt = false

[functions.shopify-oauth]
verify_jwt = false

[functions.shopify-webhook]
verify_jwt = false

[functions.shopify-compliance]
verify_jwt = false

[functions.ebay-oauth]
verify_jwt = false

[functions.ebay-notifications]
verify_jwt = false

[functions.submit-contact]
verify_jwt = false

[functions.submit-application]
verify_jwt = false


[functions.inspectabike-oauth]
verify_jwt = false

[functions.cycle-courier-order-sync]
verify_jwt = true
