# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d52c487746eb16b8782a7328435a59b6"
name = "VDMS"
application_url = "https://api.velodealer.com/functions/v1/shopify-install"
embedded = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "https://api.velodealer.com/functions/v1/shopify-compliance"

[auth]
redirect_urls = [
  "https://api.velodealer.com/functions/v1/shopify-oauth"
]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_inventory,read_inventory,read_locations,read_orders,read_products,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false
